### ISSUE TITLE
Connection instance 'get' method seems like it should be private

### ISSUE THREAD

**Issue by dfaulken** [umts/microservices-engine#15]
Since it's called by the class `get` method.

**Comment by ennukee** [comment]
Fair enough. Realistically, they should both be private since everyone will likely call the method through the engine module, i.e. `MicroservicesEngine.get(...)` rather than `MicroservicesEngine::Connection.get(...)`

**Comment by dfaulken** [comment]
Except that if it's private you can't call it from _anywhere_ else. So the class method shouldn't be.

**Comment by ennukee** [comment]
Oh right, duh

**Comment by dfaulken** [comment]
This came up again today.

**Comment by ennukee** [comment]
So @dfaulken, since we aren't just calling the method in the class method, this is causing some issues to turn it private. Since we're looking up the correct connection object then re-calling `.get` on that, it's treating as if it's being called from the outside, so the call is failing as it's private. Should we just leave them both as public then?

**Comment by ennukee** [comment]
Closing for now because of the above comment (tests are still failing when I don't think they should be because of the `private`)
